spring:
  application:
    name: eureka-server
server:
  port: 8761

eureka:

  renewalPercentThreshold: 0.85

  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}